In [13]:
import numpy as np

**Numpy** provides a convenient interface to work with array structures. It provides an array called ndarray short for n-dimensional array. It is mostly implemented in C. It uses contiguous blocks of memory that can be efficiently cached by the CPU. This comes at a cost, the arrays have a fixed size and are homogeneous.

## Python for loop approach

In [2]:
def python_forloop_list_approach(x, w):
    z = 0.
    for i in range(len(x)):
        z += x[i]*w[i]
    return z

a = [1., 2., 3.]
b = [4., 5., 6.]

print(python_forloop_list_approach(a,b))

large_a = list(range(1000))
large_b = list(range(1000))

%timeit python_forloop_list_approach(large_a, large_b)

32.0
84.8 μs ± 2.87 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Using numpy

In [3]:
import numpy as np

def numpy_dot_product(x, w):
    return x.dot(w)

large_a = np.arange(1000)
large_b = np.arange(1000)
%timeit numpy_dot_product(large_a, large_b)

1.58 μs ± 28 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
a = [1., 2., 3.]
np.array(a)


array([1., 2., 3.])

In [7]:
lst = [[1,2,3], 
       [4,5,6]]

ary2d = np.array(lst)
ary2d
ary2d.dtype

dtype('int64')

In [12]:
int32ary = ary2d.astype(np.int32)
print(int32ary.dtype)
print(ary2d.ndim)
print(ary2d.shape)


int32
2
(2, 3)


## Array construction Routines

In [15]:
np.ones((3,4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [16]:
np.zeros((4,5), dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [20]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])